/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  safelist: [
    'bg-glucose-normal/10', 'bg-glucose-normal/20', 'bg-glucose-normal/30', 'text-glucose-normal', 'border-glucose-normal/30',
    'bg-glucose-high/10', 'bg-glucose-high/20', 'bg-glucose-high/30', 'text-glucose-high', 'border-glucose-high/30',
    'bg-glucose-low/10', 'bg-glucose-low/20', 'bg-glucose-low/30', 'text-glucose-low', 'border-glucose-low/30',
    'bg-chart-carbs/10', 'bg-chart-carbs/20', 'text-chart-carbs', 'border-chart-carbs/30',
    'bg-chart-insulin/10', 'bg-chart-insulin/20', 'text-chart-insulin', 'border-chart-insulin/30',
    'bg-text-secondary/20', 'text-text-secondary',
    'bg-chart-carbs/20',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#56f1c3',
        'surface-tint': '#3edeb2',
        'glucose-normal': '#2DD4A8',
        'glucose-high': '#FBBF24',
        'glucose-low': '#FB7185',
        'surface-bright': '#333b37',
        'border-default': 'rgba(45, 212, 168, 0.15)',
        'border-strong': 'rgba(45, 212, 168, 0.30)',
        'border-subtle': 'rgba(45, 212, 168, 0.08)',
        'surface-container-lowest': '#09100d',
        'surface-container-low': '#161d1a',
        'surface-container': '#1a211e',
        'surface-container-high': '#242c28',
        'surface-container-highest': '#2f3633',
        'surface-base': '#0D1B16',
        'surface-raised': '#132B23',
        'surface-overlay': '#1A3D32',
        'surface-input': '#0A1410',
        'surface-dim': '#0e1512',
        background: '#0e1512',
        surface: '#0e1512',
        outline: '#85948d',
        'outline-variant': '#3c4a44',
        tertiary: '#ffcfad',
        'chart-carbs': '#38BDF8',
        'chart-insulin': '#A78BFA',
        'text-primary': '#E8F5F0',
        'text-secondary': '#8BA89F',
        'text-muted': '#4A6B60',
        'on-surface': '#dde4df',
        'on-background': '#dde4df',
        'on-primary': '#00382a',
        'primary-container': '#2dd4a8',
        'on-primary-container': '#005742',
        'secondary-container': '#334c43',
        'on-secondary-container': '#a0bbaf',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '0.25rem',
        sm: '0.5rem',
        base: '4px',
        md: '1rem',
        lg: '1.5rem',
        xl: '3rem',
      },
      fontFamily: {
        body: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'body-base': ['15px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '1.2', letterSpacing: '0.1em', fontWeight: '600' }],
        'title-lg': ['22px', { lineHeight: '1.2', fontWeight: '600' }],
        'data-mono': ['13px', { lineHeight: '1', fontWeight: '500' }],
        'stat-lg': ['28px', { lineHeight: '1.2', letterSpacing: '-0.03em', fontWeight: '600' }],
        'headline-hero': ['56px', { lineHeight: '1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      transitionTimingFunction: {
        'out-strong': 'cubic-bezier(0.23, 1, 0.32, 1)',
        'in-out-strong': 'cubic-bezier(0.77, 0, 0.175, 1)',
        drawer: 'cubic-bezier(0.32, 0.72, 0, 1)',
      },
    },
  },
  plugins: [],
};
