/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  safelist: [
    'bg-glucose-normal/10', 'bg-glucose-normal/20', 'bg-glucose-normal/30', 'text-glucose-normal', 'border-glucose-normal/30',
    'bg-glucose-high/10', 'bg-glucose-high/20', 'bg-glucose-high/30', 'text-glucose-high', 'border-glucose-high/30',
    'bg-glucose-low/10', 'bg-glucose-low/20', 'bg-glucose-low/30', 'text-glucose-low', 'border-glucose-low/30',
    'bg-chart-carbs/10', 'bg-chart-carbs/20', 'text-chart-carbs', 'border-chart-carbs/30',
    'bg-chart-insulin/10', 'bg-chart-insulin/20', 'text-chart-insulin', 'border-chart-insulin/30',
    'bg-text-secondary/20', 'text-text-secondary',
    'bg-chart-carbs/20',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#4be0b4',
        'surface-tint': '#3edeb2',
        'glucose-normal': '#2DD4A8',
        'glucose-high': '#F2B33D',
        'glucose-low': '#F2708A',
        'surface-bright': '#333b37',
        'border-default': 'rgba(45, 212, 168, 0.16)',
        'border-strong': 'rgba(45, 212, 168, 0.32)',
        'border-subtle': 'rgba(45, 212, 168, 0.09)',
        'surface-container-lowest': '#060d0b',
        'surface-container-low': '#101c17',
        'surface-container': '#15211c',
        'surface-container-high': '#1e2c26',
        'surface-container-highest': '#293632',
        'surface-base': '#081210',
        'surface-raised': '#0e1e19',
        'surface-overlay': '#143028',
        'surface-input': '#060d0b',
        'surface-dim': '#0a1411',
        background: '#0a1411',
        surface: '#0a1411',
        outline: '#85948d',
        'outline-variant': '#3c4a44',
        tertiary: '#ffcfad',
        'chart-carbs': '#4FB8E8',
        'chart-insulin': '#A78BFA',
        'text-primary': '#EDF7F2',
        'text-secondary': '#9CB8AD',
        'text-muted': '#648577',
        'on-surface': '#dde4df',
        'on-background': '#dde4df',
        'on-primary': '#03291e',
        'primary-container': '#2dd4a8',
        'on-primary-container': '#005742',
        'secondary-container': '#334c43',
        'on-secondary-container': '#a0bbaf',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.25rem',
        full: '9999px',
      },
      spacing: {
        xs: '0.25rem',
        sm: '0.5rem',
        base: '4px',
        md: '1rem',
        lg: '1.5rem',
        xl: '3rem',
      },
      fontFamily: {
        display: ['Fraunces', 'Georgia', 'serif'],
        body: ['Instrument Sans', 'system-ui', 'sans-serif'],
        mono: ['Spline Sans Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'body-base': ['15px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '1.2', letterSpacing: '0.1em', fontWeight: '600' }],
        'title-lg': ['22px', { lineHeight: '1.2', fontWeight: '600' }],
        'data-mono': ['13px', { lineHeight: '1', fontWeight: '500' }],
        'stat-lg': ['28px', { lineHeight: '1.2', letterSpacing: '-0.03em', fontWeight: '600' }],
        'headline-hero': ['56px', { lineHeight: '1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      boxShadow: {
        raise: 'var(--shadow-raise)',
        pop: 'var(--shadow-pop)',
        glow: 'var(--shadow-glow)',
      },
      transitionTimingFunction: {
        'out-strong': 'cubic-bezier(0.23, 1, 0.32, 1)',
        'in-out-strong': 'cubic-bezier(0.77, 0, 0.175, 1)',
        drawer: 'cubic-bezier(0.32, 0.72, 0, 1)',
      },
    },
  },
  plugins: [],
};
